### ISSUE TITLE
csvgrep -m with non-ascii pattern gives UnicodeDecodeError

### ISSUE THREAD

**Issue by spivachek** [onyxfish/csvkit#422] opened 2015-06-15 20:16 UTC
This works ok:

```bash
echo -e 'name\nsome Вася' | csvgrep -c name -m some
```

But this gives UnicodeDecodeError:

```bash
echo -e 'name\nsome Вася' | csvgrep -c name -m ася
```

Possibly pattern is converted to unicode with ascii by default? Use utf-8 maybe.

**Comment by jpmckinney** [comment] 2016-01-23 02:01
I can't reproduce on master. Likely fixed by #486, for same reason as #477.

**Closed by jpmckinney** 2016-01-23 02:01 UTC
