### ISSUE TITLE
Conflict with python-dateutil 2.3

### ISSUE THREAD

**Issue by and3k** [onyxfish/csvkit#370] opened 2015-01-04 01:29 UTC
Is there a reason why csvkit needs python-dateutil==2.2? I had 2.3 installed and needed to downgrade to 2.2 to get it working.

Keep up the great work!

Thanks,
Bela

Error when using python-dateutil 2.3:

```
$ in2csv 
Traceback (most recent call last):
  File "/usr/lib64/python3.3/site-packages/pkg_resources/__init__.py", line 567, in _build_master
    ws.require(__requires__)
  File "/usr/lib64/python3.3/site-packages/pkg_resources/__init__.py", line 876, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib64/python3.3/site-packages/pkg_resources/__init__.py", line 767, in resolve
    raise VersionConflict(tmpl % args)
pkg_resources.VersionConflict: python-dateutil 2.3 is installed but python-dateutil==2.2 is required by ['csvkit']

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python-exec/python3.3/in2csv", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib64/python3.3/site-packages/pkg_resources/__init__.py", line 2957, in <module>
    working_set = WorkingSet._build_master()
  File "/usr/lib64/python3.3/site-packages/pkg_resources/__init__.py", line 569, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/usr/lib64/python3.3/site-packages/pkg_resources/__init__.py", line 582, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/usr/lib64/python3.3/site-packages/pkg_resources/__init__.py", line 761, in resolve
    raise DistributionNotFound(req)
pkg_resources.DistributionNotFound: python-dateutil==2.2
```

**Comment by onyxfish** [comment] 2015-01-24 01:21
I don't believe so, but dateutil has previously introduced breaking changes rather suddenly so I've been leery of the >= spec. I'll take a look at 2.3 and likely upgrade. Thanks for opening an issue!

**Comment by mtrbean** [comment] 2015-01-30 21:56
I'm running into the same issue.

**Comment by hlin117** [comment] 2015-09-13 03:24
I'm running into this issue too

**Comment by iveksl2** [comment] 2015-09-14 05:16
Running into same pkg_resources issue after installation attempting to run `in2csv` command. Thx

**Comment by iveksl2** [comment] 2015-09-16 04:44
Per Installation Instructions after I run
`pip install --upgrade setuptools` the issue is resolved for me!

**Comment by HendryLi** [comment] 2015-10-30 08:43
I'm running into this issue too.Finally,I found that's due to some other packages' installtion uninstalling python-dateutil-2.2. After reinstall the csvkit, all work fine!

**Comment by jpmckinney** [comment] 2016-01-30 18:49
Note: python-dateutil may be entirely gone soon #490

**Comment by jpmckinney** [comment] 2016-01-31 18:08
Closing in favor of #490 and #497.

**Closed by jpmckinney** 2016-01-31 18:08 UTC
Labels: best-practice, Normal Priority
