### ISSUE TITLE
csvjoin includes the join field twice

### ISSUE THREAD

**Issue by mwotton** [onyxfish/csvkit#419] opened 2015-06-11 08:02 UTC
```
orb ➜  ~  csvjoin -c a <(echo "a,b\n1,2\n") <(echo "a,c\n3,4\n1,5")
a,b,a,c
1,2,1,5
```

it is probably never useful to include the join field twice.

**Comment by gromgit** [comment] 2015-07-09 06:33
Duplicate of #210

**Comment by jpmckinney** [comment] 2016-01-22 23:54
Indeed it is a dup.

**Closed by jpmckinney** 2016-01-22 23:54 UTC
