### ISSUE TITLE
Broken if has some weird unicode characters 

### ISSUE THREAD

**Issue by chuanconggao** [onyxfish/csvkit#431] opened 2015-07-31 17:45 UTC
Given a TSV with some weird unicode characters, it will break into multiple lines.
```
$ cat test.tsv
time	id	ip	postal	title
2015-07-11 19:58:14-04:00	ed915nt97hner	24.114.79.106	M6M	ððððððððððð
```

For example, if I use `csvjson`:
```json
$ cat test.tsv | csvjson -t -u 0 --stream
{
    "time": "2015-07-11 19:58:14-04:00",
    "id": "ed915nt97hner",
    "ip": "24.114.79.106",
    "postal": "M6M",
    "title": "ðððððððððð"
},
{
    "time": "ð",
    "id": null,
    "ip": null,
    "postal": null,
    "title": null
}
```

However, my own code works fine.
```python
#! /usr/bin/env python
# -*- coding: utf-8 -*-

from __future__ import print_function

import sys
import json
import csv

with open(sys.argv[1]) as f2:
    for l2 in csv.reader(f2, delimiter="\t", quoting=csv.QUOTE_MINIMAL):
        print(json.dumps(dict(zip(["time", "uid", "ip", "postal", "title"], l2))))
```

BTW, `csvjson` is also more than 10 times slower than my own code here on a huge TSV with millions of records. Any reason?

**Comment by jpmckinney** [comment] 2016-01-23 01:55
I can't reproduce. My output is:

    {"time": "2015-07-11", "id": "19:58:14-04:00", "ip": "ed915nt97hner", "postal": "24.114.79.106", "title": "M6M"}

**Comment by onyxfish** [comment] 2016-01-23 02:01
Very possible this was fixed in the agate refactor. Closing. Please reopen if its still an issue.

**Closed by onyxfish** 2016-01-23 02:01 UTC

**Comment by chuanconggao** [comment] 2016-01-23 03:51
Thanks. It seems it is fixed now. BTW, when will the csvkit be updated? The current version keeps install python-dateutil 2.2. I think the requirements could be updated.

**Comment by jpmckinney** [comment] 2016-01-23 04:01
I'm currently sprinting on some issues, so maybe after that we can possibly have a 1.0.0-alpha.
